################################################################################
#' @description Basic exploration 
#' @return 
################################################################################
#' Clear environment
rm(list = ls())
#' Libraries
library(tidyr)
library(dplyr)
library(haven)
#' Inputs
# hdss_final_all2: livebirth and stillbirth records from the HDSS
hdss <- read_dta("./data/ACSU5MR_FILES/hdss_final_all2.dta")
# survey_final_all2: livebirth and stillbirth records from the survey
survey <- read_dta("./data/ACSU5MR_FILES/survey_final_all2.dta")
# overall: linked file (it contains the match variable (match_level))
overall <- read_dta("./data/ACSU5MR_FILES/overall.dta")
################################################################################

nrow(hdss) # 2275
nrow(survey) # 2612
nrow(overall) # 2353

# What uniquely identifies children in survey
length(unique(survey$serial)) # 2612
length(unique(survey$uid_c)) # 2612

# survey child ids that are not in overall
length(survey$serial[(survey$serial %in% overall$serial)]) # 262
length(survey$serial[!(survey$serial %in% overall$serial)]) # 262
length(survey$uid_c[!(survey$uid_c %in% overall$uid_c)]) # 262
# why are these not in overall file?
# if i add them to nrow(overall), 
2353+262 # 2615
# there are 3 more observations than in survey

# check for duplicated survey ids in overall
sum(duplicated(overall$serial)) # 3
sum(duplicated(overall$uid_c)) # 3
# seems like three survey id's were matched to same record in survey

# child id's in survey that were matched to multiple HDSS
v_dup <- overall$serial[which(duplicated(overall$serial))]
length(v_dup) # 3
#View(subset(overall, serial %in% v_dup))
subset(survey, serial %in% v_dup)

# for the individuals matched to multiple HDSS records,
# can i extract the child HDSS ID?
v_duphdss <- subset(overall, serial %in% v_dup)$uid_c
length(v_duphdss) # 6
nrow(subset(hdss, uid_c %in% v_duphdss)) # 2
# don't understand why only two individuals found in HDSS dataset

# what uniquely identifies children in hdss
length(unique(hdss$cid_c)) # 1924 # nope, i think not unique because there are a bunch of missings
length(unique(hdss$uid_c)) # 2275
length(unique(hdss$uid_c_dss)) # 2275
all(hdss$uid_c == hdss$uid_c_dss) # uid_c and uid_c_dss are the same
# this seems to be an autogenerated id variable for each record in HDSS

# HDSS child ids that are not in overall
length(hdss$uid_c[!(hdss$uid_c %in% overall$uid_c)]) # 251
length(hdss$uid_c[!(hdss$uid_c %in% overall$uid_c_dss)]) # 561
length(hdss$uid_c_dss[!(hdss$uid_c_dss %in% overall$uid_c_dss)]) # 561
# these are records that the validation study wasn't matched to i think
# i think should use uid_c_dss for both, giving the higher number of non matches.

# hdss variable that are in overall
names(hdss)[which(names(hdss) %in% names(overall))]

# survey names that are in overall
names(survey)[which(names(survey) %in% names(overall))]

# hdss variable that are not in overall
names(hdss)[which(!(names(hdss) %in% names(overall)))]
# survey names that are not
names(survey)[which(!(names(survey) %in% names(overall)))]

# these missing names from both hdss and survey seem to be in overall, just with suffixes
# overall names that are not in either hdss or survey
names(overall)[which(!(names(overall) %in% c(names(hdss), names(survey))))]

# Survey ------------------------------------------------------------------

nrow(survey) # 2612
length(unique(survey$serial1)) # 836
length(unique(survey$serial)) # 2612, sequential count
length(unique(survey$`_index`)) # 836 women
length(unique(survey$`_index1`)) # 2612 children

# need to convert labels to factors

# Includes
# va1-va7: recode of major cause (Icd10_n). column number aligns with sample number found in 1
# sample : age strata
# sample2: cod strata
# _index appears to be a mother-level id
# _index1 is maybe child

# sbh
# c201-c213

# fph
# c215 singleton or multiple
# c219 boy or girl
# c220 dob
# c220_a dob
# c221_aa length of pregnancy unit
# c221 length of pregnancy month value
# c221_a length of pregnancy week value
# c223 pregnancy outcome
# c224 still alive
# c228 age at death unit
# c228_aa days value
# c228_bb months value
# c228_ccc years value

# x0_1 date of first visit
# x0_2 second visit
# x0_3
# x1 interview result

# Variables that are always missing
survey %>%  
  summarise(across(everything(), ~ sum(is.na(.)) / n())) %>%
  pivot_longer(cols = everything()) %>%
  filter(value == 1)

# HDSS --------------------------------------------------------------------

names(hdss)

# Includes
# dob_m : dob of mother. in overall is dob_m_dss
# f_intype: in-migration type
# rid_c, cid_c, name_c: ids and names of child (not needed)
# sex_c : sex child
# dod_c : child dod
# dob_c : child dob
# RESULT : values 1-4, not sure what they mean
# sample : age strata
# va1-va7: recode of major cause (Icd10_n). column number aligns with sample number found in 1
# parity_dss : mother's parity
# coo_m: cause of out-migration, mother
# doo_m: date of out-migration, mother
# age_out_m: mother's age at out date or survey starting date
# age_extraction_m: mother's age at data extraction date (31mar2024)
# uid_c, uid_c_dss: ids from dss

apply(hdss, 2, function(x) length(unique(x)))
# rid_m is mother_id
# there are 836 mothers here

# this is the same number as there are in survey
length(unique(survey$rid_m)) # 836

# all mothers in survey are in the HDSS file
length(unique(survey$rid_m)[unique(survey$rid_m) %in% unique(hdss$rid_m)]) # 836
length(unique(survey$rid_m)[!(unique(survey$rid_m) %in% unique(hdss$rid_m))]) # 0

# number of children reported per mother
hdss %>%
  group_by(rid_m) %>%
  summarise(n = n()) %>%
  group_by(n) %>%
  summarise(n_n = n())

# Investigate va and sample
# Mothers have multiple children and sample/va should vary across them
# Are these variables assigned at mother-level (as they were for sampling respondents) or at child level (as they should be for analysis)?
hdss %>%
  mutate(across(where(is.labelled), ~as_factor(.))) %>%
  mutate(va = coalesce(va1, va2, va3, va4, va5, va6, va7)) %>%
  group_by(rid_m) %>%
  mutate(n_va = n_distinct(va),
         n_sample = n_distinct(sample)) %>%
  filter(n_va > 1 | n_sample > 1) %>%
  select(n_va, n_sample, rid_m, cid_c, RESULT, dob_c, dod_c, va, sample) 
# There are no cases where a mother has multiple va, sample.
# Seems like va and sample assigned at mother level


# Overall -----------------------------------------------------------------

names(overall)
# among the variables in overall that are not in the other two datasets, there are three that are matching related
names(overall)[which(!(names(overall) %in% c(names(hdss), names(survey))))]
table(overall$date_diff, useNA = "always")
table(overall$match_score, useNA = "always")
overall %>%
  filter(match_level != 999) %>%
  ggplot() +
  geom_histogram(aes(match_level))

# not sure where preg_res_dss comes from
# can't find this variable in hdss dataset

# Investigate va and sample
# Mothers have multiple children and sample/va should vary across them
# Are these variables assigned at mother-level (as they were for sampling respondents) or at child level (as they should be for analysis)?
overall %>%
  mutate(across(where(is.labelled), ~as_factor(.))) %>%
  mutate(va = coalesce(va1, va2, va3, va4, va5, va6, va7)) %>%
  group_by(rid_m) %>%
  mutate(n_va = n_distinct(va),
         n_sample = n_distinct(sample),
         n_sample2 = n_distinct(sample2)) %>%
  filter(n_va > 1 | n_sample > 1 | n_sample > 2) %>%
  select(n_va, n_sample, rid_m, cid_c, preg_res_dss, dob_c_dss, va, sample, sample2) 
# There are no cases where a mother has multiple va, sample or sample2.
# Seems like va, sample, and sample2 were assigned at mother level
